
name: "PDF-Anleitungen"
version: "1.0.20"
slug: "pdf_manuals"
description: "Hochladen und Verwalten von PDF-Anleitungen für Ihre Geräte"
url: "https://github.com/yourusername/home-assistant-pdf-manuals"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
ingress: true
ingress_port: 8099
panel_icon: mdi:file-pdf-box
panel_title: "PDF-Anleitungen"
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web-Interface"
map:
  - share:rw
  - config:rw
options:
  max_upload_size_mb: 16
schema:
  max_upload_size_mb: int(1,50)
init: false
# Home Assistant API Zugriff
homeassistant_api: true
auth_api: true
hassio_api: true
